# Generated by Django 3.0.5 on 2020-04-19 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='', max_length=30)),
                ('body', models.TextField(blank=True, default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerTitleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asme_title', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('member', models.CharField(default='', max_length=1000)),
                ('model_name', models.CharField(default='', max_length=1000)),
                ('creator', models.CharField(default='', max_length=1000)),
                ('dimensions', models.CharField(default='', max_length=1000)),
                ('special_requests', models.CharField(default='', max_length=1000)),
                ('message', models.CharField(default='', max_length=20000)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='OfficerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.TextField(blank=True, default='', max_length=3000)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='printrequest.OfficerTitleModel')),
            ],
        ),
    ]
