# Generated by Django 3.0.4 on 2020-04-05 03:35

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('printrequest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('price', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='printerfile',
            name='subject',
        ),
        migrations.AddField(
            model_name='printerfile',
            name='creator',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='printerfile',
            name='dimensions',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='printerfile',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='printerfile',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='printerfile',
            name='member',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='printerfile',
            name='model_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='printerfile',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, default='', max_length=31),
        ),
        migrations.AddField(
            model_name='printerfile',
            name='special_requests',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='printerfile',
            name='message',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='printerfile',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='printrequest.Colors'),
        ),
    ]
