# Generated by Django 3.0.4 on 2020-04-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printrequest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printerfile',
            name='subject',
        ),
        migrations.AddField(
            model_name='printerfile',
            name='color',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='printerfile',
            name='creator',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='printerfile',
            name='dimensions',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='printerfile',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='printerfile',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='printerfile',
            name='member',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='printerfile',
            name='model_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='printerfile',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='printerfile',
            name='special_requests',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='printerfile',
            name='message',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
