# Generated by Django 3.0.4 on 2020-04-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printrequest', '0004_auto_20200407_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officertitlemodel',
            old_name='title',
            new_name='asme_title',
        ),
    ]
