# Generated by Django 3.0.4 on 2020-04-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printrequest', '0006_auto_20200407_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='', max_length=30)),
                ('body', models.TextField(blank=True, default='', max_length=3000)),
            ],
        ),
    ]
