# Generated by Django 3.0.4 on 2020-04-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printrequest', '0007_aboutmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutModel',
        ),
        migrations.DeleteModel(
            name='OfficerModel',
        ),
        migrations.DeleteModel(
            name='OfficerTitleModel',
        ),
    ]
